version: '3.8'
services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
